
export enum JobTitle {
  CEO = 'CEO',
  CTO = 'CTO',
  CFO = 'CFO',
  MANAGER = 'MANAGER',
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  DATA_SCIENTIST = 'DATA_SCIENTIST',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
  INTERN = 'INTERN'
}
